'use strict';
const topics=[
['Rutinas y frecuencia','Present simple · horarios','Usa el presente simple para hábitos. Con he/she/it, añade -s al verbo. Do/does forman preguntas; después de does, el verbo va en forma base. Los adverbios de frecuencia van antes del verbo principal y después de be.','I usually walk to class. / He is always early.','How often…? → Once a week / Twice a month / Four times a year.','at + hora; on + día; from… to… + intervalo.'],
['Alimentos y cantidades','Countable · uncountable','Los nombres contables admiten números y a/an en singular. Los incontables, como water, bread o milk, no llevan a/an por sí solos. Usa una unidad: a bottle of water.','There are six pears. / There is some bread.','How many + plural contable; How much + incontable.','Not many eggs / Not much milk. Para elegir entre opciones: Small, please.'],
['Ahora y planes','Present continuous · clima','Forma el presente continuo con am/is/are + verbo en -ing. Sirve para acciones en curso y planes ya organizados con una referencia futura.','She is studying now. / We are meeting on Friday.','Are they working? → Yes, they are. / No, they aren’t.','No uses una contracción afirmativa sola al final: Yes, she is. Intensificadores: very cold, really tired, pretty warm.'],
['Tu comunidad','Lugares · direcciones · precios','Near significa cerca de; between sitúa algo entre dos lugares; on introduce una calle. Usa where para un lugar y how much para un precio.','The café is between the bank and the hotel.','Where do you get on the bus? / How much is this jacket?','Lugares: bakery, library, pharmacy, supermarket, bus stop, gas station.'],
['Salud y habilidades','Have · should · can','Con he/she/it, have cambia a has en afirmaciones. En preguntas usa does + have. Después de can, should y shouldn’t usa el verbo base, sin to.','He has a headache. / Does he have a cough?','You should rest. / She can swim. / Can he drive?','Partes del cuerpo: head, neck, shoulder, elbow, wrist, knee, ankle. Síntomas: fever, cough, sore throat.'],
['El pasado de be','Was · were','Usa was con I/he/she/it y were con you/we/they. Para negar: wasn’t / weren’t. En preguntas, coloca was/were antes del sujeto.','I was busy yesterday. / They weren’t at home.','Were you tired? → Yes, I was. / Was she late? → No, she wasn’t.','Yesterday y last night indican pasado. How long pregunta por la duración.'],
['Escribir con claridad','Sujeto · verbo · párrafos','Una oración comienza con mayúscula y termina con punto. Los días, meses y el pronombre I llevan mayúscula. El sujeto indica quién; el verbo expresa acción o estado.','We visit the museum on Sundays. → We = sujeto; visit = verbo.','because = razón; and = suma; but = contraste.','La oración temática presenta la idea del párrafo. Usa comas en listas: a coat, a hat, and boots.'],
['Leer y escuchar','Idea principal · detalles','Primero identifica quién habla o de qué trata el texto. Luego busca detalles de tiempo, lugar, cantidad o actividad. La respuesta debe apoyarse en lo que lees o escuchas.','Question: When? → Busca un día o una hora. Where? → Busca un lugar.','Lee las opciones antes de escuchar. Escucha una vez por la idea general y otra por los detalles.','En lectura, subraya mentalmente la frase que justifica tu respuesta. No respondas solo por conocimientos generales.']
];
const questions=[];
function q(section,prompt,options,answer,explanation,extra={}){questions.push({id:questions.length,section,prompt,options,answer,explanation,...extra});}
[
['The shop is open ___ 8 a.m. to 5 p.m.',['at','from','on'],1,'From… to… indica el inicio y el final de un horario.'],
['Nora dislikes tea. She ___ drinks it.',['never','always','usually'],0,'Never significa nunca; corresponde a este hábito.'],
['___ do you visit your cousins? Every Sunday.',['Where','How often','How much'],1,'How often pregunta por frecuencia.'],
['I go swimming ___ a week: Tuesday and Thursday.',['two','twice','every'],1,'Twice a week significa dos veces por semana.'],
['Would you like ___ egg?',['a','an','some'],1,'Egg es contable singular y empieza con sonido vocálico: an egg.'],
['Would you like hot or cold milk?',['Cold, please.','Yes, it does.','No, I am.'],0,'Una pregunta con or pide elegir una de las alternativas.'],
['___ bread do we need?',['How many','How much','How often'],1,'Bread es incontable; se pregunta How much.'],
['There aren’t ___ tomatoes in the fridge.',['much','many','a'],1,'Tomatoes es plural contable: many.'],
['Look! The wind ___ blowing hard.',['am','are','is'],2,'The wind es singular: is + blowing.'],
['___ your parents cooking now?',['Are','Is','Do'],0,'Parents es plural; present continuous: Are… cooking?'],
['Is Elena reading? Yes, ___.',['she’s','she is','is she'],1,'En una respuesta corta afirmativa se usa she is, sin contraer.'],
['After the long walk, I am ___.',['tired very','really tired','really'],1,'El intensificador really va antes del adjetivo tired.'],
['The bank is ___ the café and the hotel.',['between','on','from'],0,'Between… and… ubica algo entre dos referencias.'],
['The bus stop is ___ our school, just a short walk away.',['near','under','from'],0,'Near expresa cercanía.'],
['___ is this notebook? It’s four dollars.',['Where','How often','How much'],2,'How much pregunta el precio.'],
['___ do we catch the train? At Central Station.',['Where','How many','How much'],0,'La respuesta da un lugar: Where.'],
['What ___ next Saturday? We have tickets for the concert.',['you do','are you doing','you are doing'],1,'Un plan organizado usa present continuous; la pregunta invierte are y you.'],
['How ___ your sister feel today?',['do','does','is'],1,'Your sister es tercera persona singular: does + feel.'],
['Does Leo ___ a sore throat?',['has','having','have'],2,'Después de does se usa have en forma base.'],
['Mia is fine today, but she ___ well yesterday.',['isn’t','wasn’t','weren’t'],1,'Yesterday pide pasado; she → wasn’t.'],
['Your ankle hurts. You shouldn’t ___ today.',['running','to run','run'],2,'Después de shouldn’t va el verbo base sin to.'],
['My uncle can ___ a truck.',['drive','drives','driving'],0,'Can + verbo base: drive.'],
['___ speak French?',['Can she','She can','Does she can'],0,'Pregunta con can: Can + sujeto + verbo base.'],
['Can you type quickly? No, ___.',['I can','I can’t','can’t'],1,'La respuesta corta negativa completa es No, I can’t.'],
['How long ___ they at the meeting yesterday?',['was','are','were'],2,'They requiere were; yesterday indica pasado.'],
['Was the lesson useful? Yes, ___.',['it is','it was','they were'],1,'El sujeto es it y la pregunta está en pasado: it was.']
].forEach(x=>q('Gramática',...x));
[
['You clean plates and cups after a meal. You ___.',['wash the dishes','take a shower','get dressed','make copies'],0,'Wash the dishes significa lavar los platos.'],
['Yogurt, cheese and milk are ___.',['grains','vegetables','dairy products','fruit'],2,'Estos alimentos pertenecen al grupo de los lácteos.'],
['A long orange vegetable is a ___.',['carrot','bean','grape','peach'],0,'Carrot significa zanahoria.'],
['There are white flakes falling from the sky. It is ___.',['sunny','snowy','windy','dry'],1,'Snowy describe un tiempo con nieve.'],
['The joint between your upper arm and forearm is your ___.',['ankle','elbow','knee','neck'],1,'Elbow es el codo.'],
['The joint just above your foot is your ___.',['shoulder','wrist','ankle','tooth'],2,'Ankle es el tobillo.'],
['You buy bread and rolls at a ___.',['bakery','library','fire station','hospital'],0,'Bakery es una panadería.'],
['A cashier needs to ___.',['repair roofs','use a cash register','drive a bus','paint walls'],1,'Use a cash register significa usar una caja registradora.'],
['A common breakfast made with oats and eaten with milk is ___.',['soup','cereal','onion','fish'],1,'Cereal es un alimento común para el desayuno.'],
['Small round purple or green fruits that grow in bunches are ___.',['coconuts','bananas','grapes','melons'],2,'Grapes son uvas; crecen en racimos.']
].forEach(x=>q('Vocabulario',...x));
[
['I like our town ___ it has quiet streets.',['because','but','or'],0,'Because introduce la razón.'],
['In “They study at night”, which word is the subject?',['study','night','They'],2,'They indica quién estudia: es el sujeto.'],
['Choose a topic sentence for a paragraph about buses, trains and taxis.',['My jacket is blue.','There are several ways to travel around my city.','I drink water.'],1,'La oración temática debe introducir el transporte en la ciudad.'],
['Which word needs a capital letter? “We play tennis on mondays.”',['play','tennis','mondays'],2,'Los días de la semana llevan mayúscula: Mondays.'],
['Choose the correctly written sentence.',['My friend is kind','my friend is kind.','My friend is kind.'],2,'Empieza con mayúscula y termina con punto.'],
['Which word needs a capital letter? “Her course starts in september.”',['course','starts','september'],2,'Los meses llevan mayúscula: September.'],
['In “Oliver works at a hotel”, which word is the verb?',['Oliver','works','hotel'],1,'Works expresa la acción del sujeto.'],
['Choose the correctly punctuated list.',['I pack socks a sweater and shoes.','I pack socks, a sweater, and shoes.','I pack, socks a sweater and shoes.'],1,'Las comas separan los elementos de una lista.']
].forEach(x=>q('Escritura',...x));
const reading='A Saturday at the library\n\nDaniel works in a bakery from Monday to Friday. On Saturdays, he takes the bus to the town library. He arrives at ten in the morning. He studies English for one hour and then reads a book about gardens. His friend Rosa works at the library. At noon, they have lunch at a small café across from the library. Daniel usually orders soup. Next Saturday, Rosa is visiting her aunt, so Daniel is going to the café with his brother.';
[
['What is the text mainly about?',['Daniel’s Saturday routine','How to bake bread','Rosa’s new house'],0,'El texto describe las actividades habituales y un plan de Daniel para el sábado.'],
['How does Daniel get to the library?',['By car','By bus','On foot'],1,'El texto dice “he takes the bus”.'],
['How long does he study English?',['Two hours','Thirty minutes','One hour'],2,'El texto dice “He studies English for one hour”.'],
['Where is the café?',['Inside the bakery','Across from the library','Behind Rosa’s house'],1,'El café está frente a la biblioteca: across from.'],
['Who is going to the café with Daniel next Saturday?',['His brother','His aunt','Rosa'],0,'La última oración indica que irá con su hermano.']
].forEach(x=>q('Lectura',...x,{passage:reading}));
[
['Listen and choose the activity.',['📖 Reading a book','🧹 Cleaning a room','🚲 Riding a bike'],2,'La persona dice “riding my bike”.','It is a beautiful morning. I am riding my bike in the park.'],
['Listen and choose the weather.',['☀️ Sunny','🌧️ Rainy','❄️ Snowy'],1,'Se oyen “umbrella” y “raining”.','Take your umbrella. It is raining outside.'],
['Listen and choose the place.',['📚 Library','🥖 Bakery','🏥 Hospital'],1,'La persona quiere comprar bread en la bakery.','We need some bread. Let us go to the bakery on River Road.'],
['Listen and choose the body part.',['🦵 Knee','💪 Shoulder','🦶 Ankle'],0,'La persona dice que le duele la knee, rodilla.','My knee hurts. I cannot bend my leg easily.'],
['Listen to the question and choose the best answer.',['At half past six.','At the pharmacy.','Twice a year.'],0,'What time pregunta por una hora.','What time do you start work?'],
['Listen to the question and choose the best answer.',['Yes, she does.','Yes, she can.','Yes, she was.'],1,'Una pregunta con can se responde con can.','Can your sister cook?'],
['Listen to the question and choose the best answer.',['Three bottles.','At eight o’clock.','On Green Street.'],0,'How much water pide una cantidad de agua; bottles proporciona una unidad.','How much water do we need for the trip?'],
['Listen to the question and choose the best answer.',['Yes, they are.','No, they don’t.','Yes, they were.'],2,'Una pregunta en pasado con were se responde con were.','Were your neighbors at home last night?']
].forEach(x=>q('Escucha',x[0],x[1],x[2],x[3],{audio:x[4]}));
const sections=['Todas','Escucha','Gramática','Vocabulario','Escritura','Lectura'];
let progress={};try{progress=JSON.parse(localStorage.getItem('a1-study-v1')||'{}');}catch{};
let view='home',filter='Todas',index=0,choice=null,checked=false,exam=null;
const app=document.getElementById('app');
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem('a1-study-v1',JSON.stringify(progress));}catch{document.getElementById('saved').textContent='No se pudo guardar el progreso en este navegador.';}}
function go(v){if(window.speechSynthesis)window.speechSynthesis.cancel();view=v;choice=null;checked=false;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));render();window.scrollTo({top:0,behavior:'smooth'});}
function home(){const done=Object.keys(progress).length;return `<div class="hero"><div><p class="eyebrow">UN POCO CADA DÍA. MÁS CONFIANZA.</p><h1>Tu siguiente paso<br>en <em>inglés.</em></h1><p class="intro">Entiende los temas, prueba lo que sabes y aprende de cada respuesta. Una guía para preparar tu prueba A1+ a tu ritmo.</p><div class="actions"><button class="primary" data-go="guide">Empezar a estudiar ↗</button><button data-go="practice">Ir a la práctica</button></div></div><div class="hero-art" aria-hidden="true"><span class="art-star">✳</span><div class="art-book"><small>YOUR ENGLISH NOTES</small><br>Hello,<br>new possibilities.<br><span style="color:#779248">a1+</span></div></div></div><div class="stats"><div><strong>8</strong><span>temas para repasar</span></div><div><strong>${questions.length}</strong><span>ejercicios originales</span></div><div><strong>${done}/${questions.length}</strong><span>ejercicios respondidos</span></div></div><div class="section-top"><h2>Un camino sencillo para prepararte</h2><span class="pill">Estudia → Practica → Comprueba</span></div><div class="cards"><article class="card"><span class="num">01 / COMPRENDER</span><h3>Guía de estudio</h3><p>Reglas claras en español, ejemplos en inglés y errores que conviene evitar.</p><button data-go="guide">Explorar los temas ↗</button></article><article class="card"><span class="num">02 / APRENDER HACIENDO</span><h3>Práctica con ayuda</h3><p>Cinco áreas, respuestas explicadas y escucha con voz del navegador.</p><button data-go="practice">Practicar ahora ↗</button></article><article class="card"><span class="num">03 / PONERTE A PRUEBA</span><h3>Simulacro completo</h3><p>Las mismas áreas de la prueba, con contenido nuevo y resultados al terminar.</p><button data-go="exam">Preparar simulacro ↗</button></article></div><div class="lesson"><h3>Una sesión de 30 minutos</h3><p>10 minutos de guía · 15 minutos de ejercicios · 5 minutos para revisar errores.</p><p class="notice">El simulacro usa el banco de práctica: sirve para repasar, no como medición independiente. La escritura evalúa reglas y organización; también tienes una actividad libre.</p></div>`;}
function guide(){return `<p class="eyebrow">01 / GUÍA DE ESTUDIO</p><h1>Comprende antes<br>de memorizar.</h1><p class="intro">Repasa las reglas y observa cómo funcionan en situaciones nuevas.</p>${topics.map((t,i)=>`<article class="lesson"><span class="num">TEMA ${String(i+1).padStart(2,'0')} · ${t[1]}</span><h2>${t[0]}</h2><p>${t[2]}</p><div class="example"><p lang="en"><strong>${t[3]}</strong></p><p class="rule">${t[4]}</p></div><p>${t[5]}</p></article>`).join('')}<article class="lesson"><h2>Tu pequeño párrafo</h2><p>Escribe 5–6 oraciones en inglés sobre tu rutina y tu barrio. Incluye una frecuencia, un lugar, una razón con because y un plan para la próxima semana.</p><textarea id="writing" aria-label="Tu párrafo en inglés" placeholder="I live in…"></textarea><details><summary>Ver lista de revisión y un ejemplo</summary><p>□ Sujeto y verbo en cada oración. □ Mayúsculas y puntos. □ Do/does y -s correctos. □ Conectores. □ Plan con am/is/are + -ing.</p><p lang="en">I live in a quiet town. I usually study in the evening. There is a bakery near my apartment. I like my neighborhood because it is peaceful. On Thursday, I am meeting a friend at the café.</p><p class="notice">Actividad de autoevaluación; no recibe una calificación automática.</p></details></article><button class="primary" data-go="practice">Pasar a la práctica →</button>`;}
function questionCard(item,selected,reveal,inExam=false){return `<article class="qcard"><span class="pill">${item.section}</span>${item.passage?`<div class="passage" lang="en">${item.passage}</div>`:''}${item.audio?`<div class="actions"><button data-audio="${item.id}">▶ Escuchar en inglés</button><button data-stop>■ Detener</button></div><p class="notice" id="audio-status" role="status">Voz sintética del navegador. Comprueba el volumen. Las ilustraciones son apoyos simbólicos.</p>${!inExam?`<details><summary>Ver transcripción como apoyo</summary><p lang="en">${item.audio}</p></details>`:''}`:''}<h3 lang="en">${item.prompt}</h3><div class="options">${item.options.map((o,i)=>`<button class="option ${selected===i?'selected':''} ${reveal&&i===item.answer?'correct':''} ${reveal&&selected===i&&i!==item.answer?'wrong':''}" data-choice="${i}" aria-pressed="${selected===i}" ${reveal?'disabled':''}><b>${String.fromCharCode(65+i)}</b><span lang="en">${o}</span></button>`).join('')}</div>${reveal?`<div class="feedback ${selected!==item.answer?'error':''}" role="status"><strong>${selected===item.answer?'¡Correcto!':'Revisa esta respuesta.'}</strong><p>${item.explanation}</p><p>Respuesta: ${String.fromCharCode(65+item.answer)}. ${item.options[item.answer]}</p></div>`:''}</article>`;}
function pool(){return questions.filter(q=>filter==='Todas'||q.section===filter);}
function practice(){const list=pool(),item=list[index];return `<p class="eyebrow">02 / PRÁCTICA CON AYUDA</p><h1>Prueba. Revisa.<br><em>Vuelve a intentar.</em></h1><div class="filters" aria-label="Filtrar por área">${sections.map(s=>`<button data-filter="${s}" class="${filter===s?'active':''}">${s}</button>`).join('')}</div><div class="section-top"><p>Ejercicio ${index+1} de ${list.length}</p><span class="pill">${Object.values(progress).filter(Boolean).length} correctos en el último intento</span></div><div class="progress"><div style="width:${(index+1)/list.length*100}%"></div></div>${questionCard(item,choice,checked)}<div class="actions"><button data-prev ${index===0?'disabled':''}>← Anterior</button><button class="primary" data-check ${choice===null||checked?'disabled':''}>Comprobar respuesta</button><button data-next>${index===list.length-1?'Volver al comienzo':'Siguiente →'}</button></div>`;}
function examView(){if(!exam)return `<p class="eyebrow">03 / SIMULACRO</p><h1>Un ensayo para<br>ganar <em>confianza.</em></h1><p class="intro">${questions.length} preguntas nuevas organizadas como la prueba: dos bloques de escucha, gramática, vocabulario, escritura y lectura.</p><div class="lesson"><h3>Antes de empezar</h3><p>Escucha: 8 · Gramática: 26 · Vocabulario: 10 · Escritura: 8 · Lectura: 5.</p><p>Tendrás hasta 120 minutos. Puedes revisar tus respuestas antes de entregar. Recibirás un punto por pregunta y un desglose por área.</p><p>Objetivo de estudio: 81 %. La nota es de práctica; no reproduce la ponderación del examen oficial.</p><p class="notice">La prueba original contiene numeraciones y totales inconsistentes. Aquí se usa una numeración continua y una puntuación transparente. No se necesitan sus audios ni imágenes.</p><button class="primary" data-start>Comenzar simulacro →</button></div>`;
if(exam.finished){const right=exam.items.filter(q=>exam.answers[q.id]===q.answer).length,pct=Math.round(right/exam.items.length*100);return `<p class="eyebrow">TUS RESULTADOS</p><h1>${pct>=81?'Buen trabajo.':'Ya sabes qué repasar.'}</h1><div class="lesson"><div class="score">${pct}%</div><p>${right} de ${exam.items.length} correctas · ${Object.keys(exam.answers).length} respondidas</p><p>Objetivo de estudio: 81 % (${Math.ceil(.81*exam.items.length)} aciertos).</p>${sections.slice(1).map(s=>{let a=exam.items.filter(q=>q.section===s);return `<p><strong>${s}</strong>: ${a.filter(q=>exam.answers[q.id]===q.answer).length}/${a.length}</p>`;}).join('')}<div class="actions"><button data-retry>Nuevo intento</button><button data-go="guide">Repasar guía</button></div></div><h2>Revisión de respuestas</h2>${exam.items.map((q,i)=>`<details class="lesson"><summary>${i+1}. ${q.prompt} · ${exam.answers[q.id]===q.answer?'Correcta':exam.answers[q.id]===undefined?'Sin responder':'Por repasar'}</summary><p>Tu respuesta: ${exam.answers[q.id]===undefined?'Sin respuesta':q.options[exam.answers[q.id]]}</p><p>Respuesta correcta: ${q.options[q.answer]}</p><p>${q.explanation}</p>${q.audio?`<p lang="en">${q.audio}</p>`:''}</details>`).join('')}`;}
const item=exam.items[exam.index];return `<p class="eyebrow">SIMULACRO EN CURSO</p><div class="section-top"><h2>Pregunta ${exam.index+1} de ${exam.items.length}</h2><span class="pill" id="timer"></span></div><p class="notice">${Object.keys(exam.answers).length} respondidas. Puedes cambiar tus respuestas antes de entregar. Al salir de esta sección el tiempo sigue corriendo; al recargar se pierde este intento.</p>${questionCard(item,exam.answers[item.id],false,true)}<div class="actions"><button data-exprev ${exam.index===0?'disabled':''}>← Anterior</button><button data-exnext ${exam.index===exam.items.length-1?'disabled':''}>Siguiente →</button><button class="primary" data-finish>Entregar ${Object.keys(exam.answers).length<exam.items.length?'(hay preguntas pendientes)':''}</button></div><details><summary>Ir a otra pregunta</summary><div class="filters">${exam.items.map((q,i)=>`<button data-jump="${i}" aria-label="Pregunta ${i+1}${exam.answers[q.id]!==undefined?', respondida':''}">${i+1}${exam.answers[q.id]!==undefined?' ✓':''}</button>`).join('')}</div></details>`;}
function render(){app.innerHTML=view==='home'?home():view==='guide'?guide():view==='practice'?practice():examView();if(view==='guide'){const field=document.getElementById('writing');try{field.value=localStorage.getItem('a1-paragraph')||'';}catch{}field.oninput=()=>{try{localStorage.setItem('a1-paragraph',field.value);}catch{}};}tick();}
function tick(){if(!exam||exam.finished)return;const left=Math.max(0,Math.ceil((exam.deadline-Date.now())/1000));const el=document.getElementById('timer');if(el)el.textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')} restantes`;if(left===0){exam.finished=true;go('exam');}}
function speak(id){const status=document.getElementById('audio-status');if(!('speechSynthesis'in window)){status.textContent='Este navegador no dispone de voz. En práctica puedes usar la transcripción; la escucha del simulacro requiere un navegador con síntesis de voz.';return;}speechSynthesis.cancel();const speech=new SpeechSynthesisUtterance(questions[id].audio);speech.lang='en-US';speech.rate=.8;const voice=speechSynthesis.getVoices().find(v=>v.lang.startsWith('en'));if(voice)speech.voice=voice;speech.onerror=()=>{if(status?.isConnected)status.textContent='No se pudo reproducir la voz. Prueba otro navegador o usa la transcripción en práctica.';};speechSynthesis.speak(speech);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const d=b.dataset;if(d.go||d.view){go(d.go||d.view);return;}if(d.audio!==undefined){speak(+d.audio);return;}if('stop'in d){if(window.speechSynthesis)speechSynthesis.cancel();return;}if(d.filter){filter=d.filter;index=0;choice=null;checked=false;}else if(d.choice!==undefined){if(view==='exam'&&exam&&!exam.finished)exam.answers[exam.items[exam.index].id]=+d.choice;else if(view==='practice'&&!checked)choice=+d.choice;}else if('check'in d&&choice!==null){checked=true;progress[pool()[index].id]=choice===pool()[index].answer;save();}else if('next'in d||'prev'in d){index='next'in d?(index+1)%pool().length:Math.max(0,index-1);choice=null;checked=false;if(window.speechSynthesis)speechSynthesis.cancel();}else if('start'in d){const ordered=['Escucha','Gramática','Vocabulario','Escritura','Lectura'];exam={items:ordered.flatMap(s=>questions.filter(q=>q.section===s)),answers:{},index:0,deadline:Date.now()+120*60*1000,finished:false};}else if('finish'in d){exam.finished=true;if(window.speechSynthesis)speechSynthesis.cancel();}else if('exnext'in d||'exprev'in d){exam.index+=('exnext'in d?1:-1);if(window.speechSynthesis)speechSynthesis.cancel();}else if(d.jump!==undefined){exam.index=+d.jump;}else if('retry'in d){exam=null;}render();});
setInterval(tick,1000);render();
